# Generated by Django 4.2.9 on 2024-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('LTP', models.FloatField(default=0)),
                ('pt_change', models.FloatField(default=0)),
                ('percentage_change', models.FloatField(default=0)),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
