# Generated by Django 4.2.9 on 2024-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_gainers', '0002_alter_company_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('permitted_to_trade', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('as_of', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('last_traded_price', models.CharField(blank=True, max_length=255, null=True)),
                ('total_traded_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('total_trades', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_day_close_price', models.CharField(blank=True, max_length=255, null=True)),
                ('high_low_price', models.CharField(blank=True, max_length=255, null=True)),
                ('week_high_low', models.CharField(blank=True, max_length=255, null=True)),
                ('open_price', models.CharField(blank=True, max_length=255, null=True)),
                ('close_price', models.CharField(blank=True, max_length=255, null=True)),
                ('table_listed_shares', models.CharField(blank=True, max_length=255, null=True)),
                ('total_paid_up_value', models.CharField(blank=True, max_length=255, null=True)),
                ('market_capitalization', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='LTP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='percentage_change',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pt_change',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
